### ISSUE TITLE
Module Structure

### ISSUE THREAD

**Issue by mparno** [CaseyLeeDowdle/TransportNets#6]
In the examples, I think it might be best to import TransportNets in the same way as tensorflow or tensorflow probability.  Instead of adding the TransportMaps source folder, we should treat TransportMaps as a module, make sure the path to the folder containing TransportNets is in the PYTHONPATH, and then import transportnets with something like:
```
import TransportNets as tn
```
or 
```
from TransportNets import Models as tnm
import TransportNets.Probability as tnp
```

This goes along with adding a top-level __init__.py file in the TransportNets folder.

**Comment by CaseyLeeDowdle** [comment]
Now importing transport_nets as a module with __init__ files for each module/sub-module. Slightly unsure how necessary __init__ files are with python 3 but I'm using the same structure as the tensor flow probability source code.
