### ISSUE TITLE
NVP Permutations

### ISSUE THREAD

**Issue by mparno** [CaseyLeeDowdle/TransportNets#8]
It looks like the permutations in the NVP class are hardcoded to [1,0].  Is that right?   Does this restrict us to 2D problems at the moment?

**Comment by natefrisch01** [comment]
Ah so in nfrisch/Euler (that I haven't merged in yet) we made this 
             ```c++
                # random permutation each layer
                perm_list = tf.random.shuffle(np.arange(0,output_dim))
                perm_list = tf.cast(perm_list,tf.int32)
                bijectors.append(tfb.Permute(permutation=perm_list))```
but I think we plan to add some way of customizing the permutation as well.

**Comment by natefrisch01** [comment]
This will probably be useful before we finish merging in the Euler branch, so I'll make a new branch real quick.

**Comment by CaseyLeeDowdle** [comment]
Can now initialize realNVP with lists of permutations and masking schemes.
